import React, { createContext, useContext, useEffect, useMemo, useState } from "react";
export type Locale = "en" | "zh-CN";
export type TranslationParams = Record<string, string | number>;
const en: Record<string,string> = {"language.english":"English","language.chinese":"Simplified Chinese","language.label":"Interface language","language.description":"Choose the language used across the Web control plane.","common.loading":"Loading…","common.save":"Save","common.cancel":"Cancel","common.delete":"Delete","common.create":"Create","common.update":"Update","common.refresh":"Refresh","common.close":"Close","common.confirm":"Confirm","common.none":"None","common.enabled":"Enabled","common.disabled":"Disabled","common.status":"Status","common.actions":"Actions","common.name":"Name","common.description":"Description","common.error":"Error","common.success":"Success"};
const zh: Record<string,string> = {"language.english":"English","language.chinese":"简体中文","language.label":"界面语言","language.description":"选择整个 Web 控制台使用的语言。","common.loading":"加载中…","common.save":"保存","common.cancel":"取消","common.delete":"删除","common.create":"创建","common.update":"更新","common.refresh":"刷新","common.close":"关闭","common.confirm":"确认","common.none":"无","common.enabled":"已启用","common.disabled":"已禁用","common.status":"状态","common.actions":"操作","common.name":"名称","common.description":"说明","common.error":"错误","common.success":"成功"};
const dictionaries: Record<Locale,Record<string,string>>={en,"zh-CN":zh};
function format(message:string,params?:TranslationParams){return message.replace(/\{(\w+)\}/g,(_,key)=>String(params?.[key]??("{"+key+"}")));}
interface I18nValue{locale:Locale;setLocale:(locale:Locale)=>void;t:(key:string,params?:TranslationParams)=>string;}
const Context=createContext<I18nValue>({locale:"en",setLocale:()=>undefined,t:key=>key});
export function I18nProvider({initialLocale="en",onLocaleChange,children}:{initialLocale?:Locale;onLocaleChange?:(locale:Locale)=>Promise<void>|void;children:React.ReactNode}){const[locale,setLocaleState]=useState<Locale>(initialLocale);useEffect(()=>setLocaleState(initialLocale),[initialLocale]);useEffect(()=>{document.documentElement.lang=locale},[locale]);const value=useMemo<I18nValue>(()=>({locale,setLocale:(next)=>{setLocaleState(next);void onLocaleChange?.(next)},t:(key,params)=>format(dictionaries[locale][key]??dictionaries.en[key]??key,params)}),[locale,onLocaleChange]);return <Context.Provider value={value}>{children}</Context.Provider>}
export function useI18n(){return useContext(Context)}
export function defineTranslations(values:Record<string,{en:string;"zh-CN":string}>){for(const[key,value]of Object.entries(values)){dictionaries.en[key]=value.en;dictionaries["zh-CN"][key]=value["zh-CN"]}}
