import { afterEach, describe, expect, it } from "vitest";
import { createDefaultConfig } from "../src/config.js";
import { openCorvusDatabase, type CorvusDatabase } from "../src/db/connection.js";
import { ensureDatabase } from "../src/db/migrations.js";
import { EventLog } from "../src/harness/event-log.js";
import { RunStore } from "../src/harness/run-store.js";
import { EvidenceStore } from "../src/harness/evidence-store.js";
import { ApprovalService } from "../src/harness/approval-service.js";
import { startWebControlPlane } from "../src/web/server.js";
import { BundleService } from "../src/bundle-service.js";
import { mkdtemp, rm } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";

let db: CorvusDatabase | undefined;
let close: (() => Promise<void>) | undefined;
afterEach(async () => { await close?.(); if (db?.open) db.close(); close = undefined; db = undefined; delete process.env.CORVUS_WEBHOOK_TEST; });

describe("local web control plane", () => {
  it("serves shared project/provider state and registers projects", async () => {
    db = openCorvusDatabase(":memory:");
    ensureDatabase(db);
    const config = createDefaultConfig();
    config.installation = { bundle: "full", permissionPreset: "balanced", features: ["durable-harness","filesystem","shell","git","web","memory","skills","delegation","workspaces","mcp-client","mcp-importer","mcp-server","scheduler","browser","channels","execution-nodes","webui"] };
    config.providers = { deepseek: { id: "deepseek", protocol: "openai-chat", endpoint: "https://api.deepseek.com/v1", apiKey: "key", models: ["deepseek-chat"], defaultModel: "deepseek-chat" } };
    config.mainProviderId = "deepseek";
    process.env.CORVUS_WEBHOOK_TEST = "hook-secret";
    config.channels = { telegram: { id: "telegram", type: "telegram", enabled: true, projectId: "pending", tokenRef: "env:CORVUS_WEBHOOK_TEST" }, hook: { id: "hook", type: "webhook", enabled: true, projectId: "pending", tokenRef: "env:CORVUS_WEBHOOK_TEST" } };
    const events = new EventLog(db);
    const runs = new RunStore(db, events);
    const evidence = new EvidenceStore(db, events);
    const approvals = new ApprovalService(db, events, config.permissions, evidence);
    let activeProject = "";
    const bundleRoot = await mkdtemp(join(tmpdir(), "corvus-web-bundle-"));
    const bundles = new BundleService(bundleRoot, config, async () => undefined);
    const switchedModels: Array<{ sessionId: string; providerId: string; model: string }> = [];
    const web = await startWebControlPlane({ config, runs, approvals, bundles, db, saveConfig: async () => undefined, port: 0, auth: false, activeProjectId: () => activeProject, selectProject: async (projectId) => { activeProject = projectId; return Boolean(runs.getProject(projectId)); }, switchSessionModel: (sessionId, providerId, model) => { switchedModels.push({ sessionId, providerId, model }); const context = config.providers?.[providerId]?.modelSettings?.[model]?.contextWindowTokens ?? config.contextWindowTokens; return runs.setSessionModel(sessionId, providerId, model, context); }, dispatchProjectMessage: async (projectId, prompt) => ({ runId: "run_web", content: projectId + ":" + prompt, pendingApprovals: 0 }), sendSessionMessage: async (_sessionId, prompt, onChunk) => { onChunk?.("stream:"); onChunk?.(prompt); return { content: "done" }; }, resolveApproval: async (_approvalId, _decision, _scope) => ({ resumed: true, runId: "run_approval", sessionId: null }) });
    close = web.close;
    const shell = await fetch(web.url).then((response) => response.text());
    expect(shell).toContain("<div id=\"root\">");
    const state = await fetch(web.url + "api/state").then((response) => response.json());
    const hierarchy = await fetch(web.url + "api/v1/agents/tree").then((response) => response.json());
    expect(hierarchy).toMatchObject({ level: "master", children: expect.any(Array) });
    expect(state.providers.deepseek.defaultModel).toBe("deepseek-chat");
    expect(state.permissionPreset).toBe("balanced");
    const autonomous = await fetch(web.url + "api/permissions/preset", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ preset: "autonomous" }) }).then((response) => response.json());
    expect(autonomous).toMatchObject({ ok: true, permissionPreset: "autonomous" });
    expect(config.installation?.permissionPreset).toBe("autonomous");
    expect(new Set(Object.values(config.permissions.rules))).toEqual(new Set(["allow"]));
    await fetch(web.url + "api/permissions/preset", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ preset: "balanced" }) });
    const approvalResult = await fetch(web.url + "api/approvals/approval_web", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ decision: "allow", scope: "always" }) }).then((response) => response.json());
    expect(approvalResult).toMatchObject({ ok: true, resumed: true, runId: "run_approval" });
    const catalog = await fetch(web.url + "api/v1/bundles/catalog").then((response) => response.json());
    expect(catalog.presets.map((item: any) => item.id)).toEqual(["minimal", "default", "full", "custom"]);
    const plan = await fetch(web.url + "api/v1/bundles/plan", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ preset: "full" }) }).then((response) => response.json());
    expect(plan.resolvedComponents).toContain("browser");
    const project = await fetch(web.url + "api/projects", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ name: "Vault", path: "D:/codexproject/vault" }) }).then((response) => response.json());
    expect(project.name).toBe("Vault");
    config.channels.hook.projectId = project.id; config.channels.telegram.projectId = project.id;
    const telegram = await fetch(web.url + "api/channels/telegram/inbound", { method: "POST", headers: { "content-type": "application/json", authorization: "Bearer hook-secret" }, body: JSON.stringify({ message: { message_id: 7, date: 1767225600, text: "telegram hello", from: { id: 2 }, chat: { id: 3 } } }) }).then(response=>response.json()); expect(telegram).toMatchObject({ content: project.id + ":telegram hello" });
    expect(runs.resolveChannelSession("telegram","3")?.projectId).toBe(project.id);
    const unauthorized = await fetch(web.url + "api/webhooks/hook", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ prompt: "hello" }) });
    expect(unauthorized.status).toBe(401);
    const authorized = await fetch(web.url + "api/webhooks/hook", { method: "POST", headers: { "content-type": "application/json", authorization: "Bearer hook-secret", "x-corvus-nonce": "nonce-1", "x-corvus-timestamp": String(Date.now()) }, body: JSON.stringify({ prompt: "hello" }) }).then((response) => response.json());
    expect(authorized).toMatchObject({ runId: "run_web", content: project.id + ":hello" });
    const replay = await fetch(web.url + "api/webhooks/hook", { method: "POST", headers: { "content-type": "application/json", authorization: "Bearer hook-secret", "x-corvus-nonce": "nonce-1", "x-corvus-timestamp": String(Date.now()) }, body: JSON.stringify({ prompt: "hello" }) }); expect(replay.status).toBe(409);
    const duplicateMessage = await fetch(web.url + "api/webhooks/hook", { method: "POST", headers: { "content-type": "application/json", authorization: "Bearer hook-secret", "x-corvus-nonce": "nonce-2", "x-corvus-timestamp": String(Date.now()) }, body: JSON.stringify({ prompt: "hello", messageId: "fixed-message" }) }); expect(duplicateMessage.status).toBe(202);
    const duplicateAgain = await fetch(web.url + "api/webhooks/hook", { method: "POST", headers: { "content-type": "application/json", authorization: "Bearer hook-secret", "x-corvus-nonce": "nonce-3", "x-corvus-timestamp": String(Date.now()) }, body: JSON.stringify({ prompt: "hello", messageId: "fixed-message" }) }); expect(duplicateAgain.status).toBe(409);
    const minimalPlan = await fetch(web.url + "api/v1/bundles/plan", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ preset: "minimal" }) }).then((response) => response.json());
    await fetch(web.url + "api/v1/bundles/apply", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ planId: minimalPlan.id, expectedRevision: minimalPlan.basedOnRevision }) });
    expect(config.installation?.bundle).toBe("minimal");
    const disabledBrowser = await fetch(web.url + "api/browser/pages");
    expect(disabledBrowser.status).toBe(404); expect(await disabledBrowser.json()).toMatchObject({ error: { code: "CAPABILITY_DISABLED", feature: "browser" } });
    expect(config.permissions.rules["capability:process"]).toBe("ask");

    const provider = await fetch(web.url + "api/providers", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ id: "openai", label: "OpenAI", protocol: "openai-responses", endpoint: "https://api.openai.com/v1", apiKey: "key", model: "gpt-5" }) }).then((response) => response.json());
    expect(provider.protocol).toBe("openai-responses");
    await fetch(web.url + "api/providers/openai/main", { method: "POST" });
    const role = await fetch(web.url + "api/roles", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ id: "architect", label: "Architect", providerId: "openai", model: "gpt-5" }) }).then((response) => response.json());
    expect(role.providerId).toBe("openai");
    await fetch(web.url + "api/projects/active", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ projectId: project.id }) });
    const hierarchicalDispatch = await fetch(web.url + "api/v1/dispatches", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ target: { kind: "project", id: project.id }, prompt: "hierarchy task" }) }).then((response) => response.json());
    expect(hierarchicalDispatch).toMatchObject({ content: project.id + ":hierarchy task" });
    const dispatch = await fetch(web.url + "api/dispatch", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ projectId: project.id, prompt: "inspect project" }) }).then((response) => response.json());
    expect(dispatch).toMatchObject({ runId: "run_web", content: project.id + ":inspect project" });
    const session = await fetch(web.url + "api/projects/" + project.id + "/sessions", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ name: "Web chat" }) }).then((response) => response.json());
    config.providers!.deepseek.models.push("deepseek-reasoner");
    config.providers!.deepseek.modelSettings = { "deepseek-reasoner": { contextWindowTokens: 131072 } };
    const switched = await fetch(web.url + "api/sessions/" + session.id + "/model", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ providerId: "deepseek", model: "deepseek-reasoner" }) }).then((response) => response.json());
    expect(switched).toMatchObject({ providerId: "deepseek", model: "deepseek-reasoner", contextWindowTokens: 131072 });
    expect(switchedModels).toEqual([{ sessionId: session.id, providerId: "deepseek", model: "deepseek-reasoner" }]);
    expect(runs.getSession(session.id)).toMatchObject({ providerId: "deepseek", model: "deepseek-reasoner" });
    const invalidSwitch = await fetch(web.url + "api/sessions/" + session.id + "/model", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ providerId: "deepseek", model: "missing" }) });
    expect(invalidSwitch.status).toBe(400);
    const operation = await fetch(web.url + "api/sessions/" + session.id + "/messages", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ prompt: "hello stream" }) }).then((response) => response.json());
    await new Promise((resolve) => setImmediate(resolve));
    const streamResponse = await fetch(web.url + "api/operations/" + operation.operationId + "/events");
    const reader = streamResponse.body!.getReader(); const decoder = new TextDecoder(); let streamed = "";
    while (!streamed.includes("event: complete")) { const next = await reader.read(); if (next.done) break; streamed += decoder.decode(next.value); }
    await reader.cancel();
    expect(streamed).toContain("stream:");
    expect(streamed).toContain("hello stream");
    const activeOpCheck = await fetch(web.url + "api/sessions/" + session.id + "/active-operation").then((response) => response.json());
    expect(activeOpCheck).toMatchObject({ active: expect.any(Boolean) });
    const contextCheck = await fetch(web.url + "api/sessions/" + session.id + "/context").then((response) => response.json());
    expect(contextCheck).toHaveProperty("activeOperationId");
    const cancelRes = await fetch(web.url + "api/sessions/" + session.id + "/cancel", { method: "POST" });
    expect(cancelRes.status).toBe(200);
    const cancelJson = await cancelRes.json();
    expect(cancelJson).toMatchObject({ ok: true });
    const after = await fetch(web.url + "api/state").then((response) => response.json());
    expect(after).toHaveProperty("activeOperations");
    expect(after.projects).toEqual([expect.objectContaining({ name: "Vault" })]);
    expect(after.mainProviderId).toBe("openai");
    expect(after.roles.architect.providerId).toBe("openai");
    const globalSkill = await fetch(web.url + "api/skills", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ id: "web-managed", name: "Web Managed", triggers: ["managed"], toolsRequired: ["read_file"], body: "# Web Managed\nRules", scope: "global" }) });
    expect(globalSkill.status).toBe(201);
    const invalidProjectSkill = await fetch(web.url + "api/skills", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ id: "bad-project", name: "Bad", body: "# Bad", scope: "project", projectId: "missing" }) });
    expect(invalidProjectSkill.status).toBe(400);
    const summary = await fetch(web.url + "api/projects/" + project.id + "/summary").then((response) => response.json()) as any;
    expect(summary).toMatchObject({ branch: expect.any(String), clean: expect.any(Boolean), tasks: expect.any(Array) });
    config.installation!.features.push("mcp-client");
    const invalidMcp = await fetch(web.url + "api/mcp/config", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ id: "invalid", config: {} }) });
    expect(invalidMcp.status).toBe(400);
    const reloadMcp = await fetch(web.url + "api/mcp/reload", { method: "POST" });
    expect(reloadMcp.status).toBe(200);
    const deletedSkill = await fetch(web.url + "api/skills/web-managed", { method: "DELETE" });
    expect(deletedSkill.status).toBe(200);
    await rm(bundleRoot, { recursive: true, force: true });
  });
});
