import React, { useEffect, useState } from "react";
import { getJson, postJson } from "../api";
import { Card } from "../components";

interface Bundle { id: "minimal"|"default"|"full"; label: string; description: string; features: string[]; }
interface Plugin { id:string; manifest?:{name:string;version:string;description?:string}; enabled:boolean; configured:boolean; health:string; grantedCapabilities:string[]; missingCapabilities:string[]; error?:string; }
export function InstallationPage(){
 const [catalog,setCatalog]=useState<Bundle[]>([]); const [current,setCurrent]=useState<any>(); const [plugins,setPlugins]=useState<Plugin[]>([]); const [plan,setPlan]=useState<any>(); const [message,setMessage]=useState(""); const [custom,setCustom]=useState<string[]>([]);
 const reload=async()=>{const [c,s,p]=await Promise.all([getJson<any>("/api/v1/bundles/catalog"),getJson<any>("/api/v1/bundles/current"),getJson<Plugin[]>("/api/v1/plugins")]);setCatalog(c.presets);setCurrent(s);setPlugins(p)};
 useEffect(()=>{void reload()},[]);
 const preview=async(id:string)=>setPlan(await postJson("/api/v1/bundles/plan",{preset:id,...(id==="custom"?{components:custom}:{})}));
 const features=[...new Set(catalog.flatMap(item=>item.features))].sort();
 const apply=async()=>{if(!plan)return;const result=await postJson<any>("/api/v1/bundles/apply",{planId:plan.id,expectedRevision:plan.basedOnRevision});setMessage(result.restartRequired?"Preset applied. Restart Corvus to activate every component.":"Preset applied.");setPlan(undefined);await reload()};
 const toggle=async(p:Plugin)=>{await postJson(`/api/v1/plugins/${encodeURIComponent(p.id)}/${p.enabled?"disable":"enable"}`);await reload()};
 return <div className="grid"><Card title="Installation Profile"><p>Current bundle: <b>{current?.bundle??"default"}</b></p><p style={{color:"var(--text-muted)"}}>Feature bundles and permission presets are independent. Applying Full never auto-approves tools.</p><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(190px,1fr))",gap:12}}>{catalog.map(b=><article key={b.id} style={{border:"1px solid var(--border-dark)",padding:12}}><b>{b.label}</b><p>{b.description}</p><small>{b.features.join(", ")}</small><br/><button onClick={()=>void preview(b.id)}>Preview</button></article>)}</div><details style={{marginTop:12}}><summary>Custom capability set</summary><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(180px,1fr))",gap:6,marginTop:8}}>{features.map(feature=><label key={feature}><input type="checkbox" checked={custom.includes(feature)} onChange={event=>setCustom(event.target.checked?[...custom,feature]:custom.filter(item=>item!==feature))}/>{feature}</label>)}</div><button disabled={!custom.length} onClick={()=>void preview("custom")}>Preview custom</button></details>{plan&&<div style={{marginTop:16,border:"1px solid var(--amber-bright)",padding:12}}><b>Plan: revision {plan.basedOnRevision} → {plan.preset}</b><p>Add features: {plan.add.join(", ")||"None"}</p><p>Remove features: {plan.remove.join(", ")||"None"}</p><p>New capabilities requiring review: {plan.requiredCapabilities.join(", ")||"None"}</p><button onClick={()=>void apply()}>Apply preset</button></div>}{message&&<p>{message}</p>}</Card><Card title="Plugins"><p style={{color:"var(--text-muted)"}}>Installed, enabled, configured and authorized are separate states.</p>{plugins.length?plugins.map(p=><article key={p.id} style={{borderTop:"1px solid var(--border-dark)",padding:"10px 0"}}><b>{p.manifest?.name??p.id}</b> <code>{p.manifest?.version}</code><p>{p.manifest?.description}</p><small>Health: {p.health} · grants: {p.grantedCapabilities.join(", ")||"none"}{p.missingCapabilities.length?" · missing: "+p.missingCapabilities.join(", "):""}</small>{p.error&&<p style={{color:"var(--danger)"}}>{p.error}</p>}<br/><button onClick={()=>void toggle(p)}>{p.enabled?"Disable":"Enable"}</button></article>):<p>No user plugins installed. Bundled capabilities remain available through the selected profile.</p>}</Card></div>
}
