import React, { useState } from "react";
import { Card, Modal, toast } from "../components";
import { deleteJson, postJson } from "../api";
import type { PageProps } from "./shared";

export function SkillsPage({ state, reload }: PageProps) {
  const [open,setOpen]=useState(false); const [busy,setBusy]=useState(false);
  const [form,setForm]=useState({id:"",name:"",triggers:"",tools:"",body:"# Instructions\n",scope:"global"});
  const create=async(e:React.FormEvent)=>{e.preventDefault();setBusy(true);try{await postJson("/api/skills",{id:form.id,name:form.name,title:form.name,triggers:form.triggers.split(",").map(v=>v.trim()).filter(Boolean),toolsRequired:form.tools.split(",").map(v=>v.trim()).filter(Boolean),body:form.body,scope:form.scope,projectId:form.scope==="project"?state.activeProjectId:undefined});setOpen(false);await reload();toast.success("Skill created.")}catch(err){toast.error("Failed to create skill: "+String(err))}finally{setBusy(false)}};
  const remove=async(id:string)=>{if(!window.confirm(`Delete user skill “${id}”?`))return;try{await deleteJson("/api/skills/"+encodeURIComponent(id));await reload();toast.success("Skill deleted.")}catch(err){toast.error("Failed to delete skill: "+String(err))}};
  return <><div className="page-toolbar"><button className="primary" onClick={()=>setOpen(true)}>＋ CREATE SKILL</button></div><div className="grid"><Card title={`Installed Agent Skills (${state.skills.length})`}>{state.skills.length?state.skills.map(skill=>{const builtin=skill.tier==="builtin"||skill.isBuiltin;return <article className="skill-card" key={skill.id}><div><div className="skill-title"><b>📜 {skill.title||skill.name}</b><span className="scope-badge">{builtin?"BUILT-IN SYSTEM":skill.tier==="workspace"?"CURRENT PROJECT":"GLOBAL USER"}</span></div>{skill.description&&<p>{skill.description}</p>}<code>ID: {skill.id}</code>{skill.triggers?.length>0&&<p className="skill-meta">TRIGGERS: {skill.triggers.join(", ")}</p>}{skill.toolsRequired?.length>0&&<p className="skill-meta">TOOLS: {skill.toolsRequired.join(", ")}</p>}</div>{!builtin&&<button className="danger" onClick={()=>void remove(skill.id)}>DELETE</button>}</article>}):<p className="empty-state">No skills found in workspace or global directory.</p>}</Card></div>{open&&<Modal title="Create Agent Skill" onClose={()=>setOpen(false)}><form onSubmit={create}><div className="form-columns"><label>SKILL ID<input required pattern="[a-z0-9][a-z0-9-]*" value={form.id} onChange={e=>setForm(v=>({...v,id:e.target.value}))} placeholder="code-review"/></label><label>DISPLAY NAME<input required value={form.name} onChange={e=>setForm(v=>({...v,name:e.target.value}))} placeholder="Code Review"/></label></div><div className="form-columns"><label>TRIGGERS <small>comma-separated</small><input value={form.triggers} onChange={e=>setForm(v=>({...v,triggers:e.target.value}))} placeholder="review, audit"/></label><label>TOOLS <small>comma-separated</small><input value={form.tools} onChange={e=>setForm(v=>({...v,tools:e.target.value}))} placeholder="read, grep"/></label></div><label>SCOPE<select value={form.scope} onChange={e=>setForm(v=>({...v,scope:e.target.value}))}><option value="global">Global user</option><option value="project" disabled={!state.activeProjectId}>Current project{!state.activeProjectId?" (none active)":""}</option></select></label><label>MARKDOWN BODY<textarea className="markdown-editor" required rows={14} value={form.body} onChange={e=>setForm(v=>({...v,body:e.target.value}))}/></label><div className="form-actions"><button type="button" onClick={()=>setOpen(false)}>CANCEL</button><button className="primary" disabled={busy}>{busy?"CREATING…":"CREATE SKILL"}</button></div></form></Modal>}</>;
}
