import { randomUUID } from "node:crypto";
import type { CorvusDatabase } from "./db/connection.js";
import { nextCronTime } from "./cron.js";
export type AutomationTrigger = { type: "interval"; everySeconds: number } | { type: "event"; event: string } | { type: "cron"; expression: string } | { type: "once"; at: string };
export interface AutomationConfig { id:string;label?:string;enabled:boolean;projectId:string;roleId?:string;prompt:string;trigger:AutomationTrigger;approvalMode?:"normal"|"auto-approve-readonly";timeoutSeconds?:number;overlap?:"skip"|"allow";maxRetries?:number;retryDelaySeconds?:number }
export interface AutomationState { id:string;lastRunAt?:string;nextRunAt?:string;lastStatus?:"succeeded"|"failed"|"skipped";lastError?:string;running?:boolean }
export interface AutomationRun { id:string;automationId:string;status:string;startedAt:string;completedAt?:string|null;error?:string|null }
export class AutomationScheduler {
 private timers=new Map<string,NodeJS.Timeout>(); private states=new Map<string,AutomationState>(); private running=new Set<string>();
 constructor(private readonly dispatch:(automation:AutomationConfig)=>Promise<void>,private readonly db?:CorvusDatabase){}
 start(automations:AutomationConfig[]):void{this.stop();for(const automation of automations){if(!automation.enabled||automation.trigger.type==="event")continue;if(automation.trigger.type==="interval"){const seconds=Math.max(10,automation.trigger.everySeconds);const timer=setInterval(()=>void this.run(automation),seconds*1000);timer.unref?.();this.timers.set(automation.id,timer);this.states.set(automation.id,{...this.states.get(automation.id),id:automation.id,nextRunAt:new Date(Date.now()+seconds*1000).toISOString()});continue;}const at=automation.trigger.type==="cron"?nextCronTime(automation.trigger.expression):new Date(automation.trigger.at);const delay=at.getTime()-Date.now();if(!Number.isFinite(delay)||delay<0)continue;const timer=setTimeout(()=>{void this.run(automation).finally(()=>{if(automation.trigger.type==="cron")this.startOneCron(automation)})},delay);timer.unref?.();this.timers.set(automation.id,timer);this.states.set(automation.id,{...this.states.get(automation.id),id:automation.id,nextRunAt:at.toISOString()})}}
 async emit(event:string,automations:AutomationConfig[]):Promise<void>{await Promise.all(automations.filter(item=>item.enabled&&item.trigger.type==="event"&&item.trigger.event===event).map(item=>this.run(item)))}
 async runNow(automation:AutomationConfig):Promise<void>{await this.run(automation)}
 private startOneCron(automation:AutomationConfig):void{if(automation.trigger.type!=="cron")return;const at=nextCronTime(automation.trigger.expression);const timer=setTimeout(()=>{void this.run(automation).finally(()=>this.startOneCron(automation))},Math.max(0,at.getTime()-Date.now()));timer.unref?.();this.timers.set(automation.id,timer);this.states.set(automation.id,{...this.states.get(automation.id),id:automation.id,nextRunAt:at.toISOString()})}
 listStates():AutomationState[]{return[...this.states.values()]}
 listRuns(automationId?:string,limit=100):AutomationRun[]{if(!this.db)return[];const cols="id, automation_id, status, started_at, completed_at, error";const rows=automationId?this.db.prepare("select "+cols+" from automation_runs where automation_id=? order by started_at desc limit ?").all(automationId,limit):this.db.prepare("select "+cols+" from automation_runs order by started_at desc limit ?").all(limit);return(rows as any[]).map(r=>({id:r.id,automationId:r.automation_id,status:r.status,startedAt:r.started_at,completedAt:r.completed_at,error:r.error}))}
 stop():void{for(const timer of this.timers.values())clearInterval(timer);this.timers.clear()}
 private acquireClaim(automation:AutomationConfig,runId:string,startedAt:string,claimToken:string,leaseExpiresAt:string):boolean{if(!this.db)return true;return this.db.transaction(()=>{if(automation.overlap!=="allow"){const existing=this.db!.prepare("select id from automation_runs where automation_id=? and status='running' and lease_expires_at > ? limit 1").get(automation.id,startedAt);if(existing)return false;this.db!.prepare("update automation_runs set status='failed',completed_at=?,error='Lease expired before recovery' where automation_id=? and status='running' and lease_expires_at <= ?").run(startedAt,automation.id,startedAt)}this.db!.prepare("insert into automation_runs (id,automation_id,status,started_at,completed_at,error,attempt,claim_token,lease_expires_at) values (?,?,'running',?,null,null,1,?,?)").run(runId,automation.id,startedAt,claimToken,leaseExpiresAt);return true})()}
 private async run(automation:AutomationConfig):Promise<void>{if(this.running.has(automation.id)&&automation.overlap!=="allow"){this.states.set(automation.id,{...this.states.get(automation.id),id:automation.id,lastStatus:"skipped",lastError:"Previous run is still active",running:true});return}this.running.add(automation.id);const startedAt=new Date().toISOString();const runId="auto_"+randomUUID().replace(/-/g,"");const claimToken=randomUUID();const leaseExpiresAt=new Date(Date.now()+Math.max(30,automation.timeoutSeconds??300)*1000).toISOString();if(!this.acquireClaim(automation,runId,startedAt,claimToken,leaseExpiresAt)){this.running.delete(automation.id);this.states.set(automation.id,{id:automation.id,lastRunAt:startedAt,lastStatus:"skipped",lastError:"Another process owns the active lease",running:false});return}const state:AutomationState={id:automation.id,lastRunAt:startedAt,running:true};const heartbeat=this.db?setInterval(()=>{const nextLease=new Date(Date.now()+Math.max(30,automation.timeoutSeconds??300)*1000).toISOString();this.db!.prepare("update automation_runs set lease_expires_at=? where id=? and claim_token=? and status='running'").run(nextLease,runId,claimToken)},15000):undefined;heartbeat?.unref?.();try{const timeout=automation.timeoutSeconds?new Promise<never>((_,reject)=>setTimeout(()=>reject(new Error("Automation timed out")),automation.timeoutSeconds!*1000)):undefined;let attempt=0;const maxRetries=Math.max(0,automation.maxRetries??0);for(;;){try{await(timeout?Promise.race([this.dispatch(automation),timeout]):this.dispatch(automation));break}catch(error){if(attempt>=maxRetries)throw error;attempt++;this.db?.prepare("update automation_runs set attempt=? where id=? and claim_token=?").run(attempt+1,runId,claimToken);await new Promise(resolve=>setTimeout(resolve,Math.max(1,automation.retryDelaySeconds??5)*1000))}}state.lastStatus="succeeded";this.db?.prepare("update automation_runs set status='succeeded',completed_at=? where id=? and claim_token=?").run(new Date().toISOString(),runId,claimToken)}catch(error){state.lastStatus="failed";state.lastError=(error as Error).message;this.db?.prepare("update automation_runs set status='failed',completed_at=?,error=? where id=?").run(new Date().toISOString(),state.lastError,runId)}finally{if(heartbeat)clearInterval(heartbeat);this.running.delete(automation.id);state.running=false;if(automation.trigger.type==="interval")state.nextRunAt=new Date(Date.now()+Math.max(10,automation.trigger.everySeconds)*1000).toISOString();else if(automation.trigger.type==="cron")state.nextRunAt=nextCronTime(automation.trigger.expression).toISOString();this.states.set(automation.id,state)}}
}
