import { mkdir, readFile, rename, writeFile } from "node:fs/promises";
import { join } from "node:path";
import { randomUUID } from "node:crypto";
import type { CorvusConfig } from "./config.js";
import { BUNDLES, type BundleId } from "./bundles.js";

export interface BundleState { schemaVersion:1;preset:BundleId;requestedComponents:string[];resolvedComponents:string[];revision:number;installedBy:"cli"|"webui"|"installer"|"legacy";updatedAt:string;restartRequired:boolean }
export interface ManagedBundlePlan { id:string;preset:BundleId;basedOnRevision:number;requestedComponents:string[];resolvedComponents:string[];add:string[];remove:string[];unchanged:string[];requiredCapabilities:string[];restartRequired:boolean;expiresAt:string }
const DEPENDENCIES:Record<string,string[]>={webui:["durable-harness"],delegation:["durable-harness"],workspaces:["durable-harness"],memory:["durable-harness"],skills:["durable-harness"],"mcp-client":["durable-harness"],"mcp-server":["durable-harness"],scheduler:["delegation"],channels:["delegation"],browser:["webui"],"execution-nodes":["durable-harness"]};
const CAPS:Record<string,string[]>={filesystem:["filesystem.read","filesystem.write"],shell:["process"],web:["network"],memory:["memory.read","memory.write"],delegation:["agent.delegate"],"mcp-client":["plugin","process"],"mcp-server":["network.listen"],scheduler:["scheduler.execute"],browser:["browser.control","network"],channels:["network","messaging.send"],"execution-nodes":["process.remote"]};
export class BundleService {
 private plans=new Map<string,ManagedBundlePlan>();
 constructor(private readonly root:string,private readonly config:CorvusConfig,private readonly persistConfig:()=>Promise<void>){}
 catalog(){return{schemaVersion:1,presets:[...Object.values(BUNDLES),{id:"custom",label:"Custom",description:"Choose an explicit capability set.",features:[],pluginDefaults:[]}],dependencies:DEPENDENCIES}}
 async current():Promise<BundleState>{try{const value=JSON.parse(await readFile(this.path(),"utf8")) as BundleState;if(value.schemaVersion!==1)throw new Error("Unsupported bundle schema");return value}catch(error){if((error as NodeJS.ErrnoException).code!=="ENOENT")throw error;const features=this.config.installation?.features??BUNDLES.full.features;return{schemaVersion:1,preset:this.config.installation?.bundle??"full",requestedComponents:[...features],resolvedComponents:[...features],revision:0,installedBy:"legacy",updatedAt:new Date(0).toISOString(),restartRequired:false}}}
 async plan(preset:BundleId,components?:string[]):Promise<ManagedBundlePlan>{const current=await this.current();const requested=preset==="custom"?(components??[]):stringPreset(preset);if(preset==="custom"&&requested.length===0)throw new Error("Custom bundle requires components");const resolved=resolveDependencies(requested);const known=new Set([...Object.values(BUNDLES).flatMap(item=>item.features),...Object.keys(DEPENDENCIES)]);for(const id of resolved)if(!known.has(id))throw new Error("Unknown bundle component: "+id);const currentSet=new Set(current.resolvedComponents),nextSet=new Set(resolved);const plan:ManagedBundlePlan={id:"bundle_"+randomUUID().replace(/-/g,""),preset,basedOnRevision:current.revision,requestedComponents:[...requested],resolvedComponents:resolved,add:resolved.filter(x=>!currentSet.has(x)),remove:current.resolvedComponents.filter(x=>!nextSet.has(x)),unchanged:resolved.filter(x=>currentSet.has(x)),requiredCapabilities:[...new Set(resolved.filter(x=>!currentSet.has(x)).flatMap(x=>CAPS[x]??[]))],restartRequired:true,expiresAt:new Date(Date.now()+10*60_000).toISOString()};this.plans.set(plan.id,plan);return plan}
 async apply(planId:string,expectedRevision:number,installedBy:BundleState["installedBy"]):Promise<BundleState>{const plan=this.plans.get(planId);if(!plan)throw new Error("Unknown or expired bundle plan");if(Date.parse(plan.expiresAt)<Date.now()){this.plans.delete(planId);throw new Error("Bundle plan expired");}const current=await this.current();if(current.revision!==expectedRevision||plan.basedOnRevision!==current.revision)throw Object.assign(new Error("Bundle revision conflict"),{code:"REVISION_CONFLICT"});const next:BundleState={schemaVersion:1,preset:plan.preset,requestedComponents:plan.requestedComponents,resolvedComponents:plan.resolvedComponents,revision:current.revision+1,installedBy,updatedAt:new Date().toISOString(),restartRequired:true};await this.writeAtomic(next);this.config.installation={...(this.config.installation??{}),bundle:next.preset,features:[...next.resolvedComponents],permissionPreset:this.config.installation?.permissionPreset??"balanced",updatedAt:next.updatedAt};await this.persistConfig();this.plans.delete(planId);return next}
 async acknowledgeRestart():Promise<void>{const current=await this.current();if(!current.restartRequired)return;await this.writeAtomic({...current,restartRequired:false})}
 private path(){return join(this.root,"bundle.json")}
 private async writeAtomic(value:BundleState){await mkdir(this.root,{recursive:true});const temp=this.path()+"."+process.pid+".tmp";await writeFile(temp,JSON.stringify(value,null,2)+"\n","utf8");await rename(temp,this.path())}
}
function stringPreset(id:BundleId):string[]{if(id==="custom")return[];return[...BUNDLES[id].features]}
function resolveDependencies(requested:string[]):string[]{const result=new Set<string>();const visit=(id:string,stack:string[])=>{if(stack.includes(id))throw new Error("Bundle dependency cycle: "+[...stack,id].join(" -> "));for(const dependency of DEPENDENCIES[id]??[])visit(dependency,[...stack,id]);result.add(id)};for(const id of requested)visit(id,[]);return[...result]}
