import { randomUUID } from "node:crypto";
import type { CorvusDatabase } from "./db/connection.js";
import { resolveSecret } from "./secrets.js";
export interface ChannelAdapter{type:string;deliver(config:Record<string,unknown>,payload:unknown):Promise<void>}
export interface DeliveryRow{id:string;channelId:string;status:"pending"|"delivered"|"failed";attempts:number;lastError:string|null;createdAt:string;updatedAt:string}
function text(payload:unknown):string{if(typeof payload==="string")return payload;const value=payload as any;return value?.content??value?.text??JSON.stringify(payload)}
async function post(url:string,headers:Record<string,string>,body:unknown,label:string,fetchImpl:typeof fetch=fetch){const response=await fetchImpl(url,{method:"POST",headers:{"content-type":"application/json",...headers},body:JSON.stringify(body)});const raw=await response.text();if(!response.ok)throw new Error(label+" failed: "+response.status+" "+raw);if(label==="Slack"&&raw){try{const parsed=JSON.parse(raw);if(parsed.ok===false)throw new Error(label+" failed: "+String(parsed.error??"unknown"))}catch(error){if((error as Error).message.startsWith("Slack failed"))throw error}}}
export class OutboundWebhookAdapter implements ChannelAdapter{type="webhook";async deliver(config:Record<string,unknown>,payload:unknown){const url=String(config.outboundUrl??"");if(url)await post(url,{},payload,"Outbound webhook")}}
export class TelegramAdapter implements ChannelAdapter{type="telegram";async deliver(config:Record<string,unknown>,payload:unknown){const token=resolveSecret(String(config.credentialRef??""));await post("https://api.telegram.org/bot"+token+"/sendMessage",{},{chat_id:String(config.targetId),text:text(payload)},"Telegram")}}
export class SlackAdapter implements ChannelAdapter{type="slack";async deliver(config:Record<string,unknown>,payload:unknown){const token=resolveSecret(String(config.credentialRef??""));await post("https://slack.com/api/chat.postMessage",{authorization:"Bearer "+token},{channel:String(config.targetId),text:text(payload)},"Slack")}}
export class DiscordAdapter implements ChannelAdapter{type="discord";async deliver(config:Record<string,unknown>,payload:unknown){await post(String(config.outboundUrl??""),{},{content:text(payload)},"Discord")}}
export class ChannelDeliveryManager{
 private adapters=new Map<string,ChannelAdapter>();private timer?:NodeJS.Timeout;private configs:()=>Record<string,Record<string,unknown>>=()=>({});
 constructor(private readonly db:CorvusDatabase){for(const adapter of [new OutboundWebhookAdapter(),new TelegramAdapter(),new SlackAdapter(),new DiscordAdapter()])this.register(adapter)}
 register(adapter:ChannelAdapter):void{this.adapters.set(adapter.type,adapter)}
 start(configs:()=>Record<string,Record<string,unknown>>,intervalMs=5000):void{this.stop();this.configs=configs;void this.processPending();this.timer=setInterval(()=>void this.processPending(),intervalMs);this.timer.unref?.()}
 stop():void{if(this.timer)clearInterval(this.timer);this.timer=undefined}
 async enqueue(channelId:string,config:Record<string,unknown>,payload:unknown):Promise<DeliveryRow>{const now=new Date().toISOString(),id="delivery_"+randomUUID().replace(/-/g,"");this.db.prepare("insert into channel_deliveries (id,channel_id,payload_json,status,attempts,last_error,created_at,updated_at) values (?, ?, ?, 'pending', 0, null, ?, ?)").run(id,channelId,JSON.stringify(payload),now,now);await this.attempt(id,config);return this.get(id)!}
 async retry(id:string,config:Record<string,unknown>):Promise<DeliveryRow>{this.db.prepare("update channel_deliveries set status='pending',updated_at=? where id=?").run(new Date().toISOString(),id);await this.attempt(id,config);return this.get(id)!}
 async processPending(limit=20):Promise<void>{const rows=this.db.prepare("select id,channel_id from channel_deliveries where status in ('pending','failed') and attempts < 5 order by updated_at asc limit ?").all(limit) as Array<{id:string;channel_id:string}>;for(const row of rows){const config=this.configs()[row.channel_id];if(config)await this.attempt(row.id,config)}}
 list(limit=100):DeliveryRow[]{return(this.db.prepare("select id,channel_id,status,attempts,last_error,created_at,updated_at from channel_deliveries order by updated_at desc limit ?").all(limit)as any[]).map(r=>({id:r.id,channelId:r.channel_id,status:r.status,attempts:r.attempts,lastError:r.last_error,createdAt:r.created_at,updatedAt:r.updated_at}))}
 private get(id:string){return this.list(1000).find(row=>row.id===id)}
 private async attempt(id:string,config:Record<string,unknown>){const row=this.db.prepare("select payload_json,attempts from channel_deliveries where id=?").get(id)as{payload_json:string;attempts:number}|undefined;if(!row)throw new Error("Delivery not found");const adapter=this.adapters.get(String(config.type));if(!adapter)throw new Error("Channel adapter unavailable: "+String(config.type));try{await adapter.deliver(config,JSON.parse(row.payload_json));this.db.prepare("update channel_deliveries set status='delivered',attempts=?,last_error=null,updated_at=? where id=?").run(row.attempts+1,new Date().toISOString(),id)}catch(error){this.db.prepare("update channel_deliveries set status='failed',attempts=?,last_error=?,updated_at=? where id=?").run(row.attempts+1,(error as Error).message,new Date().toISOString(),id)}}
}
