import { fork, type ChildProcess } from "node:child_process";
import { existsSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, resolve as resolvePath } from "node:path";
import { randomUUID } from "node:crypto";
import type { PluginManifest } from "./plugins.js";
import type { RegisterableTool } from "./tools/index.js";
export class WorkerPluginClient{
 private child?:ChildProcess;private pending=new Map<string,{resolve:(v:unknown)=>void;reject:(e:Error)=>void;timer:NodeJS.Timeout}>();private tools:Omit<RegisterableTool,"execute">[]=[];private lastHeartbeat=Date.now();private watchdog?:NodeJS.Timeout;
 constructor(private readonly entry:string,private readonly manifest:PluginManifest,private readonly config:unknown){}
 async start():Promise<RegisterableTool[]>{return new Promise((resolve,reject)=>{const moduleDir=dirname(fileURLToPath(import.meta.url));const localHost=resolvePath(moduleDir,"plugin-worker-host.js");const builtHost=resolvePath(process.cwd(),"dist","plugin-worker-host.js");const host=existsSync(localHost)?localHost:builtHost;this.child=fork(host,[this.entry],{execArgv:["--max-old-space-size="+Math.max(32,Math.min(1024,this.manifest.sandbox?.memoryMb??256))],stdio:["pipe","pipe","pipe","ipc"],env:{...minimalEnv(),CORVUS_PLUGIN_MANIFEST:JSON.stringify(this.manifest),CORVUS_PLUGIN_CONFIG:JSON.stringify(this.config??null),CORVUS_PLUGIN_ROOT:dirname(this.entry),CORVUS_PLUGIN_SANDBOX:JSON.stringify(this.manifest.sandbox??{filesystem:"plugin-only",network:"none",subprocess:false})}});let buffer="";const timeout=setTimeout(()=>reject(new Error("Worker plugin startup timed out")),10000);this.child.stdout?.on("data",chunk=>{buffer+=chunk.toString();const lines=buffer.split("\n");buffer=lines.pop()??"";for(const line of lines)if(line.trim())this.message(JSON.parse(line),()=>{clearTimeout(timeout);resolve(this.tools.map(tool=>({...tool,execute:input=>this.call(String((tool as any).name),input as Record<string,unknown>)})) as RegisterableTool[])})});this.child.once("error",error=>{clearTimeout(timeout);this.rejectAll(error);reject(error)});this.child.once("exit",()=>{const error=new Error("Worker plugin exited");this.rejectAll(error);reject(error)})})}
 async stop():Promise<void>{if(this.watchdog)clearInterval(this.watchdog);this.watchdog=undefined;const child=this.child;if(!child)return;const exited=new Promise<void>(resolve=>{if(child.exitCode!==null)return resolve();child.once("exit",()=>resolve())});try{await this.request({method:"shutdown"},3000)}catch{}if(child.exitCode===null)child.kill();await Promise.race([exited,new Promise<void>(resolve=>setTimeout(resolve,3000))]);this.child=undefined;this.rejectAll(new Error("Worker plugin stopped"))}
 private call(name:string,input:Record<string,unknown>):Promise<unknown>{return this.request({method:"call",name,input},30000)}
 private request(body:Record<string,unknown>,timeoutMs:number):Promise<unknown>{return new Promise((resolve,reject)=>{if(!this.child?.stdin) return reject(new Error("Worker plugin not running"));const id=randomUUID();const timer=setTimeout(()=>{this.pending.delete(id);reject(new Error("Worker plugin request timed out"))},timeoutMs);this.pending.set(id,{resolve,reject,timer});this.child.stdin.write(JSON.stringify({id,...body})+"\n")})}
 private message(message:any,onReady:()=>void){if(message.event==="heartbeat"){this.lastHeartbeat=Date.now();return}if(message.event==="tool"){this.tools.push(message.tool);return}if(message.event==="ready"){this.lastHeartbeat=Date.now();this.watchdog=setInterval(()=>{if(Date.now()-this.lastHeartbeat>15000){this.child?.kill();this.rejectAll(new Error("Worker plugin heartbeat timed out"))}},5000);this.watchdog.unref?.();onReady();return}const pending=this.pending.get(message.id);if(pending){this.pending.delete(message.id);clearTimeout(pending.timer);message.error?pending.reject(new Error(message.error)):pending.resolve(message.result)}}
 private rejectAll(error:Error){for(const value of this.pending.values()){clearTimeout(value.timer);value.reject(error)}this.pending.clear()}
}
function minimalEnv():NodeJS.ProcessEnv{return{PATH:process.env.PATH,Path:process.env.Path,SystemRoot:process.env.SystemRoot,WINDIR:process.env.WINDIR,HOME:process.env.HOME,USERPROFILE:process.env.USERPROFILE,NODE_ENV:"production"}}
